---
# common
    - name: Install MariaDB package
      yum: name={{ item }} state=installed
      loop:
        - mariadb-server
        - MySQL-python
        - libselinux-python
        - libsemanage-python
        - mariadb-server
        - apr-devel


    - name: Configure SELinux to start mysql on any port
      seboolean: name=mysql_connect_any state=true persistent=yes

    - name: Create Mysql configuration file
      template: src=my.cnf.j2 dest=/etc/my.cnf
      notify:
      #- restart mariadb
      - systemctl start mariadb.service

    - name: Create MariaDB log file
      file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

    - name: insert firewalld rule
      firewalld: port=3306/tcp permanent=true state=enabled immediate=yes
      ignore_errors: yes

    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started




    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"

    - name: Make sure there is neither a database with name 'foo', nor one with name 'bar'
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name:
          - foo
          - bar
        state: absent

    - name: Importing db
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        target: /app/dockerfiles/odesi_docker.sql
        name:
          - sp_odesi
        state: import

    # - name: remove remote root
    #   mysql_user:
    #     check_implicit_admin: true
    #     login_user: root
    #     login_password: "{{ mysql_root_password }}"
    #     user: root
    #     state: absent
