---
  - hosts: sp_ask_dashboard_dev
    remote_user: root
    become: true
    vars:
      host: "{{ inventory_hostname }}"
      project_path: "/app"

    tasks:
      - name: Test Connection
        ping:
      - name: System details
        when: ansible_distribution == 'Ubuntu' and  ansible_distribution_version == "20.04"
        debug: msg="{{ item }}"
        with_items:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"
        - "{{ ansible_distribution_release  }}"
      - name: Ansible host
        debug: 
          msg: "http://{{ ansible_ssh_host }}"

    roles: 
      - baseconf
