# Generated by Django 2.2.19 on 2021-09-22 04:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('Canned Message', 'Canned Message'), ('Library Account', 'Library Account'), ('LibraryH3lp', 'LibraryH3lp'), ('Library Website Issue', 'Library Website Issue')], max_length=32)),
                ('lh3ChatID', models.PositiveIntegerField(unique=True)),
                ('to_follow_up', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('operatorID', models.PositiveIntegerField(blank=True, null=True)),
                ('queueID', models.PositiveIntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('-lh3ChatID',),
            },
        ),
        migrations.CreateModel(
            name='chatReferenceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lh3ChatID', models.PositiveIntegerField(unique=True)),
                ('ref_question_found', models.BooleanField(blank=True, default=False, null=True)),
                ('ref_question_position', models.PositiveIntegerField(blank=True, null=True)),
                ('operatorID', models.PositiveIntegerField(blank=True, null=True)),
                ('queueID', models.PositiveIntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('-lh3ChatID',),
            },
        ),
    ]
