# Generated by Django 2.2.19 on 2021-09-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lh3ChatID',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatreferencequestion',
            name='lh3ChatID',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
