# Generated by Django 2.2.19 on 2021-09-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210922_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatLightAssessment',
        ),
        migrations.AddIndex(
            model_name='chatlightassessment',
            index=models.Index(fields=['lh3ChatID', 'queueID'], name='dashboard_c_lh3Chat_07252a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreferencequestion',
            index=models.Index(fields=['lh3ChatID', 'queueID'], name='dashboard_c_lh3Chat_780c55_idx'),
        ),
    ]
