# Generated by Django 2.2.19 on 2021-09-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210922_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlightassessment',
            name='lh3ChatID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatreferencequestion',
            name='lh3ChatID',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
