---
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
        cache_valid_time: 3600

        
    - block:
      - name: Install base packages
        package:
          name: "{{ item }}"
          state: present
        loop: "{{ packages }}"
        vars:
          packages:
            - curl
            - build-essential
            - git
            - gunicorn
            - vim
            - tree
            - supervisor
            - unzip
            - wget
            - htop
            - sysstat
            - ufw
            - ntp
            - python-is-python3
        when: ansible_pkg_mgr == 'apt'

      - name: Install base packages (suite)
        package:
          name: "{{ item }}"
          state: present
        loop: "{{ packages }}"
        vars:
          packages:
            - vim
            - make
            - gcc
            - ntp
            - yamllint
            - python3-pip
            - build-essential
            - libssl-dev
            - libffi-dev
            - libpq-dev
            - python3-setuptools
            - python3-venv
            - software-properties-common
            - neovim
            - python3-neovim
            - glances
            - zsh
            - powerline
        when: ansible_pkg_mgr == 'apt'

      - name: Remove dependencies that are no longer kequired
        apt:
          autoremove: yes
          purge: yes

      - name: Remove useless packages from the cache
        apt:
          autoclean: yes


      - name: ensure nginx is at the latest version
        apt: 
          name: nginx 
          state: latest
      
      - name: start nginx
        service:
            name: nginx
            state: started

      - name: Create locales
        locale_gen:
          name: "{{ item }}"
          state: present
        with_items:
          - en_US.UTF-8
          - fr_FR.UTF-8
        when: ansible_pkg_mgr == 'apt'

      - name: Set timezone to America/Toronto
        timezone:
          name: America/Toronto

      - name: Install utility packages
        apt:
          name:
            - nano
            - mc
            - net-tools
            - bsd-mailx
            - fail2ban
            - unattended-upgrades
            - apt-listchanges
            - needrestart
            - libpam-pwquality
            - aide
            - haveged
            - chrony
            - postfix
            - firewalld
            - man
          state: latest

    - name: Create locales
      locale_gen:
        name: "{{ item }}"
        state: present
      with_items:
        - en_US.UTF-8
        - fr_FR.UTF-8
      when: ansible_pkg_mgr == 'apt'

    - name: Set timezone to America/Toronto
      timezone:
        name: America/Toronto

    - name: Installing package for video cut
      pip:
        name: medipack

    - name: Add a setting to ~/.gitconfig
      git_config:
        name: alias.ci
        scope: global
        value: commit

    - name: Add a setting to ~/.gitconfig
      git_config:
        name: alias.st
        scope: global
        value: status

    - name: Remove a setting from ~/.gitconfig
      git_config:
        name: alias.ci
        scope: global
        state: absent

    - name: Add a setting to ~/.gitconfig
      git_config:
        name: core.editor
        scope: global
        value: vim
        
    - name: Set git user.email
      git_config:
        name: user.email
        scope: global
        value: "salfjsdl@gmail.com"

    - name: Set git user.name
      git_config:
        name: user.name
        scope: global
        value: "guins2000"





















