---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local
    become: true
    tasks:

    - name: System details
      when: ansible_distribution == 'Ubuntu' and  ansible_distribution_version == "20.04"
      debug: msg="{{ item }}"
      with_items:
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_release  }}"
      - #https://askubuntu.com/questions/59383/extract-part-of-a-video-with-a-one-line-command

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 86400 

    - block:
      - name: Install base packages
        package:
          name: "{{ item }}"
          state: present
        loop: "{{ packages }}"
        vars:
          packages:
            - git
            - vim
            - htop
            - ffmpeg
            - tree
            - make
            - gcc
            - ntp
            - yamllint
            - unzip
            - sysstat
            - curl
            - python-is-python3
            - ufw
            - neovim
            - python3-pip
            - build-essential
            - libssl-dev
            - libffi-dev
            - libpq-dev
            - python3-setuptools
            - python3-venv
            - software-properties-common
            - neovim
            - python3-neovim
            - glances
            - ghostscript
            - zsh
            - powerline
        when: ansible_pkg_mgr == 'apt'

    - name: Remove dependencies that are no longer kequired
      apt:
        autoremove: yes
        purge: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Create locales
      locale_gen:
        name: "{{ item }}"
        state: present
      with_items:
        - en_US.UTF-8
        - fr_FR.UTF-8
      when: ansible_pkg_mgr == 'apt'

    - name: Set timezone to America/Toronto
      timezone:
        name: America/Toronto

    - name: Installing package for video cut
      pip:
        name: medipack

    - name: Add a setting to ~/.gitconfig
      git_config:
        name: alias.ci
        scope: global
        value: commit

    - name: Add a setting to ~/.gitconfig
      git_config:
        name: alias.st
        scope: global
        value: status

    - name: Remove a setting from ~/.gitconfig
      git_config:
        name: alias.ci
        scope: global
        state: absent

    - name: Add a setting to ~/.gitconfig
      git_config:
        name: core.editor
        scope: global
        value: vim
        
    - name: Set git user.email
      git_config:
        name: user.email
        scope: global
        value: "salfjsdl@gmail.com"

    - name: Set git user.name
      git_config:
        name: user.name
        scope: global
        value: "guins2000"
