---
    - name: Set the hostname
      command: hostnamectl set-hostname odesidownloads-app

    - name: Python3 dependencies
      pip:
        requirements: /flask_app_project/requirements/requirements.txt

    - name: populate /etc/environment
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value}}"
      loop:
        - key: DJANGO_SUPER_USER 
          value : admin
        - key: FLASK_APP 
          value : run.py
        - key: MYSQL_ROOT_PASSWORD 
          value : "sp!ASK!2019"
        - key: MYSQL_DATABASE 
          value : sp_odesi
        - key: MYSQL_ODESI_DATABASE_HOST 
          value : localhost
        - key: MYSQL_ODESI_DATABASE_USER 
          value : root
        - key: MYSQL_ODESI_DATABASE_NAME 
          value : sp_odesi
        - key: MYSQL_ODESI_ROOT_PASSWORD 
          value : "sp!ASK!2019"
        - key: MYSQL_ODESI_PORT 
          value : 3306
        - key: MYAPP_WORKDIR 
          value : /app/
        - key: PROD_CRONJOBS_APP 
          value : "/flask_app_project/static/images/"

    - name: copy NGINX conf file
      copy:
        src: ./flask_app_nginx
        dest: /etc/nginx/sites-enabled/flask_app_nginx
      notify:
          - restart nginx

    - name: "Disable the NGINX’s default configuration file by removing its symlink"
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

